### ISSUE TITLE
Enable translations

### ISSUE THREAD

**Issue by kisphp** [klederson/microblog#5]
Add translation element in `app/config/config.yml`

``` yml
framework:
  secret: %secret%
  translator: { fallbacks: ["%locale%"] }
```
